name: Actualización contenedor

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  actualiza:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v2

      - name: Construye contenedor
      # https://github.com/marketplace/actions/build-and-push-docker-images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/barpower
          tags: latest
          Dockerfile: Dockerfile
