name: Sincronizar Readme

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
jobs:
  sincroniza:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: meeDamian/sync-readme@v1.0.6
      with:
        pass: ${{ secrets.DOCKER_PASS }}
        description: true

