name: Sincronizar Readme

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
jobs:
  sincroniza:
    runs-on: ubuntu-latest
    steps:
      - name: Sincronizar readme Github con Dockerhub
      # https://github.com/marketplace/actions/dockerhub-readme
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: ${{ secrets.DOCKER_USERNAME }}/barpower
          readme: "./README.md"
