name: Sincronizar Readme

on:
  push:
    paths:
    - "README.md"
jobs:
  sincroniza:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@master
      - name: Sincronizar readme Github con Dockerhub
      # https://github.com/marketplace/actions/docker-hub-readme-description-sync
        uses: meeDamian/sync-readme@v1.0.6
        with:
          pass: ${{ secrets.DOCKER_PASS }}
          description: true
